CREATE TABLE IF NOT EXISTS outbox (
    id UUID NOT NULL PRIMARY KEY,
    domain TEXT NOT NULL,
    kind TEXT NOT NULL,
    type TEXT NOT NULL,
    key UUID NOT NULL,
    payload BYTEA NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL
);
