[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
base = { path = "../base" }
serde_json = "1.0"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
