[package]
name = "bus"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
ctor = "0.4.2"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
